from ..core.vulnerability_models import ScanResult
import html

def generate_html_report(scan_result: ScanResult, filename: str):
    """
    Generates a professional HTML report.
    """
    
    findings_html = ""
    for finding in scan_result.findings:
        findings_html += f"""
        <div class="finding {finding.risk_level.lower()}">
            <h3>{html.escape(finding.name)} <span class="badge">{finding.risk_level}</span></h3>
            <p><strong>URL:</strong> {html.escape(finding.url)}</p>
            <p><strong>Payload:</strong> {html.escape(finding.payload)}</p>
            <p><strong>Proof:</strong> <pre>{html.escape(finding.proof)}</pre></p>
            <p><strong>Remediation:</strong> {html.escape(finding.remediation)}</p>
        </div>
        """

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>UploadForge Scan Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; background-color: #f4f4f4; }}
            h1 {{ color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }}
            .summary {{ background: white; padding: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
            .finding {{ background: white; margin-top: 20px; padding: 20px; border-radius: 5px; border-left: 5px solid #ccc; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
            .critical {{ border-left-color: #d32f2f; }}
            .high {{ border-left-color: #f57c00; }}
            .medium {{ border-left-color: #fbc02d; }}
            .low {{ border-left-color: #388e3c; }}
            .badge {{ float: right; padding: 5px 10px; border-radius: 3px; color: white; font-size: 0.8em; }}
            .critical .badge {{ background: #d32f2f; }}
            .high .badge {{ background: #f57c00; }}
            .medium .badge {{ background: #fbc02d; color: #333; }}
            .low .badge {{ background: #388e3c; }}
            pre {{ background: #eee; padding: 10px; overflow-x: auto; }}
        </style>
    </head>
    <body>
        <h1>UploadForge Scan Report</h1>
        <div class="summary">
            <h2>Scan Summary</h2>
            <p><strong>Target:</strong> {html.escape(scan_result.target)}</p>
            <p><strong>Start Time:</strong> {scan_result.start_time}</p>
            <p><strong>Total Requests:</strong> {scan_result.stats['total_requests']}</p>
            <p><strong>Vulnerabilities Found:</strong> {scan_result.stats['vulns_found']}</p>
        </div>
        
        <h2>Findings</h2>
        {findings_html}
        
        <footer>
            <p>Generated by UploadForge</p>
        </footer>
    </body>
    </html>
    """
    
    with open(filename, 'w') as f:
        f.write(html_content)
    
    print(f"HTML Report saved to {filename}")
